version: '3'
services:
  app:
    build: .
    image: melyo/rest-boilerplate-prod:1.0
    env_file: ./.env
    ports:
      - '5000:5000'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: boilerplate_prod
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_prod:/var/lib/mysql
volumes:
  mysql_prod:
    driver: local
