version: '3'
services:
  app:
    build: .
    image: melyo/rest-boilerplate-dev:1.0
    volumes:
      - .:/srv
    ports:
      - '5000:5000'
    entrypoint: npx nodemon
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: boilerplate_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - mysql_dev:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
volumes:
  mysql_dev:
    driver: local
