version: '3'
services:
  app:
    build: .
    image: melyo/rest-boilerplate-prod:1.0
    env_file: ./.env
    ports:
      - ${APP_LOCAL_PORT}:${APP_PORT}
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_prod:/var/lib/mysql
volumes:
  mysql_prod:
    driver: local
