version: '3'
services:
  app:
    build: .
    image: melyo/rest-boilerplate-dev:1.0
    volumes:
      - .:/srv
    ports:
      - ${APP_LOCAL_PORT}:${APP_PORT}
    entrypoint: npx nodemon
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    volumes:
      - mysql_dev:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST
      - PMA_PORT
    ports:
      - ${PMA_LOCAL_PORT}:80
volumes:
  mysql_dev:
    driver: local
